name: bearcord
description: BearCord — современный кросс-платформенный мессенджер
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  responsive_framework: ^1.0.0
  go_router: ^10.0.0
  dio: ^5.3.0
  url_launcher: ^6.3.2

  http: ^1.2.2

  flutter_secure_storage: ^9.0.0

  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6

  flutter_riverpod: ^2.4.0

  intl: ^0.18.0
  timeago: ^3.5.0
  image_picker: ^1.0.4
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true


flutter_native_splash:
  color: "#000000"
  image: assets/images/flash.png

  android: true
  ios: true

  android_12:
    color: "#000000"
    image: assets/images/flash.png


flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
  image_path: "assets/icon/bearcord.png"
  remove_alpha_ios: true